import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

function functionBody(source, functionName) {
  const start = source.indexOf(`function ${functionName}`);
  assert.notEqual(start, -1, `${functionName} should exist`);
  const bodyStart = source.indexOf("{", start);
  assert.notEqual(bodyStart, -1, `${functionName} should have a body`);
  let depth = 0;
  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(bodyStart + 1, index);
    }
  }
  throw new Error(`${functionName} body is incomplete`);
}

function functionSource(source, functionName) {
  const start = source.indexOf(`function ${functionName}`);
  assert.notEqual(start, -1, `${functionName} should exist`);
  const signatureEnd = source.indexOf(") {", start);
  assert.notEqual(signatureEnd, -1, `${functionName} should have a signature`);
  const bodyStart = signatureEnd + 2;
  assert.notEqual(bodyStart, -1, `${functionName} should have a body`);
  let depth = 0;
  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index];
    if (char === "{") depth += 1;
    if (char === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  throw new Error(`${functionName} body is incomplete`);
}

test("local workbench looks like a product chat surface instead of a debug panel", async () => {
  const html = await readFile("public/index.html", "utf8");

  assert.match(html, /选择项目/);
  assert.match(html, /Bridge/);
  assert.match(html, /id="outputDrawer"[^>]*hidden/);
  assert.match(html, /id="outputDrawer"[^>]*hidden[^>]*aria-hidden="true"/);
  assert.match(html, /输出/);
  assert.match(html, /themeToggle/);
  assert.match(html, /GPT 会话/);
  assert.match(html, /id="bindingState"/);
  assert.match(html, /id="syncModeText"/);
  assert.match(html, /id="routingRuleState"/);
  assert.doesNotMatch(html, /runnerModeText/);
  assert.doesNotMatch(html, /artifactCountText/);
  assert.doesNotMatch(html, /Codex 未绑定/);
  assert.match(html, /placeholder="给 GPT 发消息"/);
  assert.doesNotMatch(html, /发送给/);
  assert.doesNotMatch(html, /问 GPT/);
  assert.doesNotMatch(html, /叫 Codex/);
  assert.doesNotMatch(html, /三人同步/);
  assert.doesNotMatch(html, /targetMode/);
  assert.doesNotMatch(html, /target-switch/);
  assert.match(html, /composerFileInput/);
  assert.match(html, /composerBox/);
  assert.match(html, /composerBlockHint/);
  assert.match(html, /composer-block-hint/);
  assert.match(html, /acceptancePanel/);
  assert.match(html, /id="acceptancePanel"[^>]*hidden/);
  assert.match(html, /id="acceptanceReportButton"/);
  assert.match(html, /id="acceptanceRecordButton"/);
  assert.match(html, /id="workflowBanner"/);
  assert.match(html, /id="workflowTitle"/);
  assert.match(html, /id="workflowDetail"/);
  assert.match(html, /id="workflowNextStep"/);
  assert.match(html, /id="workflowActions"/);
  assert.match(html, /id="workflowOpenBoundChatButton"/);
  assert.match(html, /id="workflowOpenExtensionsButton"/);
  assert.match(html, /id="workflowApplyPreferencesButton"/);
  assert.match(html, /id="workflowCopyStepsButton"/);
  assert.match(html, /id="workflowRecheckButton"/);
  assert.match(html, /id="onboardingGuide"/);
  assert.match(html, /class="onboarding-guide"/);
  assert.match(html, /id="selfCheckButton"/);
  assert.match(html, /id="selfCheckPanel"/);
  assert.match(html, /id="selfCheckTitle"/);
  assert.match(html, /id="selfCheckDetail"/);
  assert.match(html, /id="selfCheckNextStep"/);
  assert.doesNotMatch(html, /<section id="selfCheckPanel"/);
  assert.match(html, /data-workflow-action="bound-chat"/);
  assert.match(html, /data-workflow-action="extension"/);
  assert.match(html, /data-workflow-action="preference"/);
  assert.match(html, /data-workflow-action="always"/);
  assert.match(html, /id="chainStatusPanel"/);
  assert.match(html, /id="chainRouteValue"/);
  assert.match(html, /id="chainSavingsValue"/);
  assert.match(html, /id="chainRuleValue"/);
  assert.match(html, /id="chainErrorValue"/);
  assert.match(html, /id="chainSummaryValue"/);
  assert.match(html, /id="chainCopyStatusButton"/);
  assert.match(html, /id="chainCopyAcceptanceRecordButton"/);
  assert.match(html, /id="acceptanceRecordDialog"/);
  assert.match(html, /id="acceptanceRecordBody"/);
  assert.match(html, /id="acceptanceRecordCopyButton"/);
  assert.match(html, /id="acceptanceRecordDownloadButton"/);
  assert.match(html, /class="chain-status-popover"/);
  const topbar = html.match(/<header class="topbar"[\s\S]*?<\/header>/)?.[0] || "";
  assert.match(topbar, /id="chainStatusPanel"/);
  assert.match(topbar, /id="selfCheckPanel"/);
  assert.match(topbar, /class="chain-status-summary"/);
  const chainPanelStart = html.indexOf('id="chainStatusPanel"');
  const chainPanelEnd = html.indexOf("</details>", chainPanelStart);
  const selfCheckIndex = html.indexOf('id="selfCheckPanel"');
  assert.ok(selfCheckIndex > chainPanelStart && selfCheckIndex < chainPanelEnd);
  assert.doesNotMatch(html, /<section id="chainStatusPanel"/);
  assert.match(html, /modeSelect/);
  assert.match(html, /modelSelect/);
  assert.match(html, /composer-box/);
  assert.match(html, /composer-footer/);
  assert.match(html, /id="previewDownloadButton"/);
  assert.match(html, /id="imagePreviewDownloadButton"/);
  assert.doesNotMatch(html, /id="previewDownloadLink"/);
  assert.doesNotMatch(html, /id="imagePreviewDownloadLink"/);
  const modeSelect = html.match(/<select id="modeSelect"[\s\S]*?<\/select>/)?.[0] || "";
  const modelSelect = html.match(/<select id="modelSelect"[\s\S]*?<\/select>/)?.[0] || "";
  assert.match(modeSelect, /value="balanced"/);
  assert.match(modeSelect, /value="high"/);
  assert.match(modeSelect, /value="pro">Pro 扩展<\/option>/);
  assert.doesNotMatch(modeSelect, /value="gpt-5\.5"/);
  assert.match(modelSelect, /value="gpt-5\.5"/);
  assert.doesNotMatch(modelSelect, /value="gpt-4\.5"/);
  assert.match(modelSelect, /value="o3"/);
  assert.doesNotMatch(modelSelect, /value="balanced"/);
  assert.doesNotMatch(html, /本机文件给 GPT/);
  assert.doesNotMatch(html, /input-row/);
  assert.doesNotMatch(html, /打开 GPT/);
  assert.doesNotMatch(html, /稳定性测试/);
  assert.doesNotMatch(html, /执行队列/);
  assert.doesNotMatch(html, /运行 Codex/);
  assert.doesNotMatch(html, /任务内容/);
  assert.doesNotMatch(html, /执行结果/);
  assert.doesNotMatch(html, /最近任务/);
  assert.doesNotMatch(html, /生成同步消息/);
  assert.doesNotMatch(html, /导入 ChatGPT 回复/);
  assert.doesNotMatch(html, /Codex 模式/);
  assert.doesNotMatch(html, /同步方式/);
  assert.doesNotMatch(html, /规划端/);
});

test("local workbench frontend supports projects, themes and rich GPT-like messages", async () => {
  const html = await readFile("public/index.html", "utf8");
  const js = await readFile("public/app.js", "utf8");
  const css = await readFile("public/styles.css", "utf8");
  const cssBlocks = (selector) =>
    Array.from(
      css.matchAll(new RegExp(`${selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{[^}]*\\}`, "g")),
      (match) => match[0],
    );

  assert.match(js, /\/api\/workspace/);
  assert.match(js, /\/api\/projects/);
  assert.match(js, /\/api\/room\/messages/);
  assert.doesNotMatch(js, /\/api\/room\/route-preview/);
  assert.match(js, /\/api\/diagnostics\/status/);
  assert.match(js, /\/api\/gpt\/preflight/);
  assert.match(js, /\/api\/acceptance\/status/);
  assert.match(js, /\/api\/acceptance\/report/);
  assert.match(js, /\/api\/acceptance\/real-browser-record/);
  assert.match(js, /\/api\/artifacts/);
  assert.match(js, /\/api\/artifacts\/import/);
  assert.match(js, /\/api\/local-files\/analyze-with-gpt/);
  assert.match(js, /composerFileInput/);
  assert.match(js, /composerBox/);
  assert.match(js, /modeSelect/);
  assert.match(js, /modelSelect/);
  assert.match(js, /handleComposerDrop/);
  assert.match(js, /handleComposerPaste/);
  assert.match(js, /modePreference/);
  assert.match(js, /modelPreference/);
  assert.match(js, /function modelSupportsModePreference/);
  assert.match(js, /function syncPreferenceControls/);
  assert.match(js, /const MODE_LABELS_BY_MODEL/);
  assert.match(js, /"gpt-5\.5":\s*\{[\s\S]*pro:\s*"Pro 扩展"/);
  assert.match(js, /"gpt-5\.4":\s*\{[\s\S]*pro:\s*"专业"/);
  assert.match(js, /function syncModeOptionLabels/);
  assert.match(js, /syncModeOptionLabels\(\)/);
  assert.match(js, /modeSelect\.disabled = !supportsModes/);
  assert.match(js, /function connectionChipLabel/);
  assert.match(js, /function connectionChipLevel/);
  assert.doesNotMatch(js, /GPT 页面忙/);
  assert.doesNotMatch(js, /status\?\.extension\?\.pageStatus\?\.code === "active_generation"/);
  assert.match(js, /els\.syncModeText\.textContent = connectionChipLabel\(status\)/);
  assert.doesNotMatch(js, /els\.syncModeText\.textContent = syncLabel\(status\)/);
  assert.doesNotMatch(html, /id="extensionDetail"/);
  assert.doesNotMatch(js, /extensionDetail/);
  assert.doesNotMatch(js, /els\.extensionStatus\.textContent = "偏好未应用"/);
  assert.doesNotMatch(js, /els\.extensionStatus\.textContent = "偏好已应用"/);
  assert.match(js, /function preferenceStatusMatchesWorkspace/);
  assert.match(js, /preferenceStatusMatchesWorkspace\(preferenceStatus, workspace\)/);
  assert.match(js, /function routingRuleLabel/);
  assert.match(js, /workspace\.bridgeRulesPath/);
  assert.match(js, /els\.routingRuleState/);
  assert.match(js, /setTimeout\(syncPreferencesToChatGpt, 120\)/);
  assert.match(js, /modePreference: selectedModePreference\(\)/);
  assert.match(js, /sendSelectedLocalFiles/);
  assert.match(js, /save-to-project/);
  assert.match(js, /analyze-with-codex/);
  assert.match(js, /analyze-with-gpt/);
  assert.match(js, /renderImageGrid/);
  assert.match(js, /gallery\.dataset\.imageCount = String\(images\.length\)/);
  assert.match(js, /railShell\.className = "image-gallery-strip"/);
  assert.match(js, /railHeader\.className = "image-gallery-strip-header"/);
  assert.match(js, /railHeader\.textContent = `\$\{images\.length\} 张图片`/);
  assert.match(js, /if \(extension === "psd"\) return false;/);
  assert.match(js, /function canPreviewArtifact/);
  assert.match(js, /canPreviewArtifact\(artifact\)/);
  assert.match(js, /loadArtifactPreview/);
  assert.match(js, /function loadArtifactPreview\(artifactId, options = \{\}\)/);
  assert.match(js, /const cacheKey = `\$\{artifactId\}:\$\{full \? "full" : "compact"\}`/);
  assert.match(js, /\/preview\$\{full \? "\?full=1" : ""\}/);
  assert.match(js, /loadArtifactPreview\(artifactId, \{ full: true \}\)/);
  assert.match(js, /function renderPreviewReader\(preview, body, options = \{\}\)/);
  assert.match(js, /preview-reader-toolbar/);
  assert.match(js, /preview-reader-body/);
  assert.match(js, /renderSpreadsheetPreview\(preview, options = \{\}\)/);
  assert.match(js, /sheet-preview-scroll/);
  assert.match(js, /renderDocumentPreview\(preview, options = \{\}\)/);
  assert.match(js, /document-preview-body/);
  assert.match(js, /renderArchivePreview\(preview, options = \{\}\)/);
  assert.match(js, /archive-filter-input/);
  assert.match(js, /renderArtifactPreviewContent\(preview, \{ compact: false, expanded: true \}\)/);
  assert.match(js, /renderArtifactPreviewShell/);
  assert.match(js, /context: "message"/);
  assert.match(js, /is-message-artifact/);
  assert.match(js, /async function downloadArtifactToDevice/);
  assert.doesNotMatch(functionBody(js, "downloadArtifactToDevice"), /fetch\(/);
  assert.match(js, /function createIconDownloadButton/);
  assert.match(js, /function createImageActions/);
  assert.match(js, /function setImageActionArtifact/);
  assert.match(js, /overlay\.append\(name, createImageActions\(artifact\)\)/);
  assert.match(js, /mainCounter\.className = "image-gallery-count"/);
  assert.match(js, /mainLabel\.append\(mainCounter, mainName\)/);
  assert.match(js, /mainCaption\.append\(mainLabel, mainActions\)/);
  assert.match(js, /function setImageGalleryActionArtifacts/);
  assert.match(js, /setImageGalleryActionArtifacts\(mainActions, images, index, \{/);
  assert.match(js, /imagePreviewDownloadButton/);
  assert.match(js, /imagePreviewCounter/);
  assert.match(js, /imagePreviewPrev/);
  assert.match(js, /imagePreviewNext/);
  assert.match(js, /function openImagePreview\(artifacts, index = 0\)/);
  assert.match(js, /renderImagePreviewDialog/);
  assert.match(js, /openImagePreview\(images, index, \{/);
  assert.match(js, /imagePreviewOnChange: null/);
  assert.match(js, /function syncImagePreviewSelection/);
  assert.match(js, /state\.imagePreviewOnChange\(safeIndex, artifact\)/);
  assert.match(js, /openImagePreview\(images, index, \{[\s\S]*onChange: \(nextIndex\) => setActive\(images\[nextIndex\], thumbs\[nextIndex\], nextIndex\)/);
  assert.match(js, /setImageGalleryActionArtifacts\(mainActions, images, index, \{[\s\S]*onChange: \(nextIndex\) => setActive\(images\[nextIndex\], thumbs\[nextIndex\], nextIndex\)/);
  assert.match(js, /event\.key === "Escape"/);
  assert.match(js, /els\.imageDialog\.close\(\)/);
  assert.match(js, /imageGallerySelection: new Map\(\)/);
  assert.match(js, /state\.imageGallerySelection\.set\(galleryKey, index\)/);
  assert.match(js, /const initialIndex = Number\.isInteger\(rememberedIndex\)/);
  assert.match(js, /const restoredScrollTop = Math\.max\(0, initialIndex \* 84 - 16\)/);
  assert.match(js, /window\.requestAnimationFrame\(\(\) => \{/);
  assert.match(js, /thumb\.setAttribute\("aria-label", `查看第 \$\{index \+ 1\} 张图片`\)/);
  assert.match(js, /thumb\.title = `查看第 \$\{index \+ 1\} 张图片`/);
  assert.doesNotMatch(js, /function setDownloadLinkTarget/);
  assert.match(js, /function artifactViewUrl/);
  assert.doesNotMatch(js, /function artifactSaveAsUrl/);
  assert.doesNotMatch(js, /function handleArtifactDownload/);
  assert.doesNotMatch(js, /\/save-as/);
  assert.match(js, /\/view/);
  assert.match(functionBody(js, "downloadArtifactToDevice"), /link\.href = artifactDownloadUrl\(artifactOrId\)/);
  assert.doesNotMatch(functionBody(js, "downloadArtifactToDevice"), /response\.blob\(\)/);
  assert.match(js, /link\.download = filename/);
  assert.doesNotMatch(js, /target = "_blank"/);
  assert.match(js, /createIconButton\("放大"/);
  assert.match(js, /actions\.append\(createIconDownloadButton\(artifact\)\)/);
  assert.match(js, /previewArtifact\(artifact\.id\)/);
  const renderFileCardBlock = js.match(/function renderFileCard\(artifact, options = \{\}\) \{[\s\S]*?\n\}/)?.[0] || "";
  assert.doesNotMatch(renderFileCardBlock, /saveArtifact|analyzeArtifactWithGpt|sendArtifactToCodex|给 GPT|给 Codex|保存/);
  assert.match(js, /previewDownloadButton/);
  assert.match(js, /previewDownloadButton\.addEventListener\("click"/);
  assert.match(js, /imagePreviewDownloadButton\.addEventListener\("click"/);
  assert.match(js, /\/preview/);
  assert.match(js, /function renderPdfPreview/);
  assert.match(js, /navpanes=0/);
  assert.match(js, /function renderDocumentPreview/);
  assert.match(js, /function renderArchivePreview/);
  assert.match(js, /function renderPreviewScopeNote/);
  assert.match(js, /Bridge 只展示摘要/);
  assert.match(js, /完整文件已交给 GPT/);
  assert.match(js, /function renderPsdPreview/);
  assert.match(js, /const TEXT_PREVIEW_EXTENSIONS = new Set/);
  assert.match(js, /function isTextPreviewArtifact/);
  assert.match(js, /TEXT_PREVIEW_EXTENSIONS\.has\(artifactExtension\(artifact\)\)/);
  assert.match(js, /canInlinePreviewArtifact[\s\S]*isTextPreviewArtifact\(artifact\)/);
  assert.match(js, /function renderTextPreview/);
  assert.match(js, /function textPreviewLanguage/);
  assert.match(js, /function formatTextPreview/);
  assert.match(js, /function isLongformTextPreview/);
  assert.match(js, /function renderLongformTextPreview/);
  assert.match(js, /function renderMarkdownLongform/);
  assert.match(js, /function renderPresentationPreview\(preview, options = {}\)/);
  assert.match(js, /const visibleSlides = options\.compact/);
  assert.match(js, /renderArtifactPreviewContent\(preview, \{ compact: true }\)/);
  assert.match(js, /renderArtifactPreviewContent\(preview, \{ compact: false, expanded: true }\)/);
  assert.match(js, /function isVisibleRoomMessage/);
  assert.match(js, /image_batch_continuation/);
  assert.match(js, /messages\.filter\(isVisibleRoomMessage\)/);
  assert.match(js, /function displayTextForMessage/);
  assert.match(js, /artifactImages\.length >= 1/);
  assert.match(js, /已捕获 \$\{artifactImages\.length\} 张图片/);
  assert.match(js, /生成了\?一张图片/);
  assert.match(js, /renderMessageStatus/);
  assert.match(js, /function syncStatusSummary/);
  assert.match(js, /function renderSyncStatusDetail/);
  assert.match(js, /function renderSyncTimeline/);
  assert.match(js, /message-status-strip/);
  assert.match(js, /message-status-summary/);
  assert.match(js, /message-status-detail/);
  assert.match(js, /message-status-grid/);
  assert.match(js, /function formatSyncProgressDuration/);
  assert.match(js, /durations\.gptThoughtMs/);
  assert.match(js, /function reliableGptThoughtMs/);
  assert.match(js, /thoughtMs > responseMs \+ 5000/);
  assert.match(js, /GPT 用时 \$\{formatDurationMs\(thoughtMs\)\}/);
  assert.match(js, /Bridge 捕获 \$\{formatDurationMs\(durations\.responseMs\)\}/);
  assert.match(js, /metadata\.syncProgress/);
  assert.match(js, /metadata\.syncStatus === "succeeded"/);
  assert.match(js, /function friendlyErrorMessage\(input = ""\)/);
  assert.match(js, /function friendlySyncStatusReason\(reason = "", syncStatus = ""\)/);
  assert.match(js, /els\.toast\.textContent = friendlyErrorMessage\(message\)/);
  assert.match(js, /const normalizedReason = friendlySyncStatusReason\(metadata\.syncReason, metadata\.syncStatus\)/);
  assert.match(js, /failed to fetch\|networkerror\|load failed/i);
  assert.match(js, /download.*timed out\|download was interrupted/i);
  assert.match(js, /renderSyncActions/);
  assert.match(js, /async function cancelSyncJob/);
  assert.match(js, /function renderWorkflowStatus/);
  assert.match(js, /function renderOnboardingGuide/);
  assert.match(js, /function selfCheckResult/);
  assert.match(js, /function renderSelfCheckPanel/);
  assert.match(js, /async function runSelfCheck/);
  assert.match(js, /function workflowRepairText/);
  assert.match(js, /extension\.sourceDir/);
  assert.match(js, /extension\.needsReload/);
  assert.match(js, /function openExtensionManager/);
  assert.match(js, /async function openExtensionManager\(status = state\.status\)/);
  assert.match(js, /const copyText = extension\.sourceDir \|\| target/);
  assert.match(js, /navigator\.clipboard\.writeText\(copyText\)/);
  assert.match(js, /openExtensionManager\(state\.status\)/);
  assert.match(js, /async function applyWorkflowPreferences/);
  assert.match(js, /function syncWorkflowActionButtons/);
  assert.match(js, /status\?\.workflowStatus/);
  assert.match(js, /status\?\.connection/);
  assert.match(js, /connection\.label/);
  assert.match(js, /canSendToGpt/);
  assert.match(js, /status \? status\.dataCoverage/);
  assert.match(js, /dataCoverage\.label/);
  assert.match(js, /status\?\.routeCoverage/);
  assert.match(js, /routeCoverage\.label/);
  assert.match(js, /payload\?\.groups/);
  assert.match(js, /route_probe/);
  assert.match(js, /workflowBanner\.dataset\.level/);
  assert.match(js, /workflowNextStep/);
  assert.match(js, /workflowActions\.hidden = !shouldShow/);
  assert.match(js, /workflowOpenBoundChatButton\.hidden = !showBoundChatAction/);
  assert.match(js, /workflowOpenExtensionsButton\.hidden = !showExtensionAction/);
  assert.match(js, /workflowApplyPreferencesButton\.hidden = !showPreferenceAction/);
  assert.match(js, /selfCheckButton\.hidden = selfCheck\.level === "ready"/);
  assert.match(js, /syncWorkflowActionButtons\(status, shouldShow\)/);
  assert.match(js, /workflowOpenBoundChatButton\.addEventListener\("click"/);
  assert.match(js, /async function openBoundChatPage/);
  assert.match(js, /workflowOpenExtensionsButton\.addEventListener\("click"/);
  assert.match(js, /window\.open\(target/);
  assert.match(js, /workflowApplyPreferencesButton\.addEventListener\("click", applyWorkflowPreferences\)/);
  assert.match(js, /await syncPreferencesToChatGpt\(\{ successToast: "已重新应用模型和模式" }\)/);
  assert.match(js, /await refreshWorkspaceSurface\(\{ scrollToBottom: false }\)/);
  assert.match(js, /workflowCopyStepsButton\.addEventListener\("click"/);
  assert.match(js, /selfCheckButton\.addEventListener\("click", runSelfCheck\)/);
  assert.match(js, /workflowRecheckButton\.addEventListener\("click"/);
  assert.match(js, /navigator\.clipboard\.writeText\(workflowRepairText\(state\.status\)\)/);
  assert.match(js, /function routeLabelForChainPanel/);
  assert.match(js, /function savingsLabelForChainPanel/);
  assert.match(js, /function renderChainStatusPanel/);
  assert.match(js, /function bridgeStatusCopyText/);
  assert.match(js, /async function loadAcceptanceRecordText/);
  assert.match(js, /async function openAcceptanceRecordPreview/);
  assert.match(js, /async function copyAcceptanceRecordFromDialog/);
  assert.match(js, /async function downloadAcceptanceRecordFromDialog/);
  assert.match(js, /chainCopyStatusButton\.addEventListener\("click"/);
  assert.match(js, /chainCopyAcceptanceRecordButton\.addEventListener\("click"/);
  assert.match(js, /acceptanceRecordCopyButton\.addEventListener\("click"/);
  assert.match(js, /acceptanceRecordDownloadButton\.addEventListener\("click"/);
  assert.match(js, /navigator\.clipboard\.writeText\(bridgeStatusCopyText\(\)\)/);
  assert.match(js, /acceptanceRecordBody\.textContent = record/);
  assert.match(js, /acceptanceRecordDialog\.showModal\(\)/);
  assert.match(js, /navigator\.clipboard\.writeText\(record\)/);
  assert.match(js, /downloadTextFile\("CodexBridge-真实验收记录\.md", record, "text\/markdown;charset=utf-8"\)/);
  assert.match(js, /Bridge 状态：/);
  assert.match(js, /function summaryLabelForChainPanel/);
  assert.match(js, /syncJob\.errorCode === "manual_cancelled"/);
  assert.match(js, /已停止/);
  assert.match(js, /els\.chainSummaryValue/);
  assert.match(js, /state\.status\?\.activeSyncJob \|\| state\.status\?\.latestSyncJob/);
  assert.match(js, /els\.chainRouteValue/);
  assert.match(js, /els\.chainSavingsValue/);
  assert.match(js, /els\.chainRuleValue/);
  assert.match(js, /els\.chainErrorValue/);
  assert.match(js, /function workflowBlocksGptSend/);
  assert.match(js, /async function loadGptPreflight/);
  assert.match(js, /function gptPreflightBlocksSend/);
  assert.match(js, /function gptPreflightBlockMessage/);
  assert.match(js, /function ensureGptSendReady/);
  assert.match(js, /function ensureGptActionReady/);
  assert.match(js, /function markGptActionControl/);
  assert.match(js, /function syncGptActionControls/);
  assert.match(js, /control\.dataset\.gptActionControl/);
  assert.match(js, /function currentComposerBlockMessage/);
  assert.match(js, /function looksLikeQuestionMarkEncodingLoss/);
  assert.match(js, /TEXT_ENCODING_LOSS_MESSAGE/);
  assert.match(js, /HIDDEN_ENCODING_LOSS_MESSAGE/);
  assert.match(js, /looksLikeQuestionMarkEncodingLoss\(text\)/);
  assert.match(js, /hasEnoughQuestionMarksToStandAlone/);
  assert.match(js, /return HIDDEN_ENCODING_LOSS_MESSAGE/);
  assert.doesNotMatch(js, /composerRouteHint/);
  assert.doesNotMatch(js, /将发送给 GPT/);
  assert.doesNotMatch(html, /composerRouteHint/);
  assert.doesNotMatch(css, /composer-route-hint/);
  assert.match(js, /function syncComposerSendControl/);
  assert.match(js, /function syncComposerBlockHint/);
  assert.match(js, /sendButton\.dataset\.composerBlocked/);
  assert.match(js, /composerBlockHint\.hidden/);
  assert.match(js, /const blockMessage = currentComposerBlockMessage\(\);[\s\S]*if \(blockMessage\) \{[\s\S]*showToast\(blockMessage\);[\s\S]*return;/);
  assert.match(js, /composerBlockHint\.textContent = blockMessage/);
  assert.match(js, /await ensureGptSendReady\(targets, text\)/);
  assert.match(js, /async function queueAcceptancePrompt[\s\S]*await ensureGptActionReady\(\)[\s\S]*sendMessage\(check\.prompt, \["gpt"\]/);
  assert.match(js, /async function analyzeArtifactWithGpt[\s\S]*await ensureGptActionReady\(\)[\s\S]*\/api\/artifacts\/\$\{encodeURIComponent\(artifactId\)\}\/analyze-with-gpt/);
  assert.match(js, /async function retrySyncJob[\s\S]*await ensureGptActionReady\(\)[\s\S]*\/api\/sync\/jobs\/\$\{encodeURIComponent\(syncJobId\)\}\/retry/);
  assert.match(js, /actions\.append\(markGptActionControl\(createButton\(/);
  const cancelActionBlock = js.match(/if \(metadata\.syncCanCancel\) \{[\s\S]*?\n  \}/)?.[0] || "";
  assert.match(cancelActionBlock, /cancelSyncJob\(metadata\.syncJobId\)/);
  assert.match(cancelActionBlock, /data-sync-cancel-control/);
  assert.doesNotMatch(cancelActionBlock, /markGptActionControl/);
  assert.match(js, /cancellingSyncJobIds: new Set\(\)/);
  assert.match(js, /state\.cancellingSyncJobIds\.add\(syncJobId\)/);
  assert.match(js, /state\.cancellingSyncJobIds\.delete\(syncJobId\)/);
  assert.match(js, /\w+Button\.disabled = true/);
  assert.match(js, /gptPreflightBlocksSend\(preflight\)/);
  assert.match(js, /gptPreflightBlockMessage\(preflight\)/);
  assert.match(js, /syncGptActionControls\(\)/);
  assert.match(js, /syncComposerSendControl\(\)/);
  assert.match(js, /chatInput\.addEventListener\("input", \(\) => \{[\s\S]*syncComposerSendControl\(\);[\s\S]*\}\);/);
  assert.doesNotMatch(js, /queueComposerRoutePreview/);
  assert.match(js, /async function importPendingComposerFiles/);
  assert.match(js, /sendMessage\(text, targets, \{\s*inputArtifactIds/s);
  assert.doesNotMatch(js, /for \(const file of files\)[\s\S]*sendLocalFileToTargets\(file, targets, text\)/);
  assert.match(js, /retrySyncJob/);
  assert.match(js, /syncCanRetry/);
  assert.doesNotMatch(js, /message\.from !== "user" \|\| !metadata\.syncStatus/);
  assert.match(js, /from === "codex"/);
  assert.match(js, /renderAcceptancePanel/);
  assert.match(js, /queueAcceptancePrompt/);
  assert.match(js, /copyAcceptanceReport/);
  assert.match(js, /downloadAcceptanceRecord/);
  assert.match(js, /downloadTextFile\("CodexBridge-真实验收记录\.md"/);
  assert.match(js, /URL\.createObjectURL\(blob\)/);
  assert.match(js, /origin: "acceptance"/);
  assert.match(js, /Codex 验收/);
  assert.match(js, /visualMessageFrom/);
  assert.match(js, /\/retry/);
  assert.match(js, /renderCodeBlocks/);
  assert.match(js, /scrollToComposer/);
  assert.match(js, /function forceElementToBottom/);
  assert.match(js, /document\.scrollingElement/);
  assert.match(js, /const BOTTOM_SCROLL_SETTLE_DELAYS_MS = \[80, 240, 600, 1200, 2200, 4200, 7600, 12000, 20000\]/);
  assert.doesNotMatch(js, /scrollIntoView\(\{ block: "end", behavior: "smooth" \}\)/);
  assert.match(js, /function captureChatScrollState/);
  assert.match(js, /function restoreChatScrollState/);
  assert.match(js, /refreshWorkspaceSurface\(\{ scrollToBottom = false \} = {}\)/);
  assert.match(js, /const chatScrollState = captureChatScrollState\(\)/);
  assert.match(js, /const previousLastMessageId = latestVisibleMessageId\(\)/);
  assert.match(js, /const nextLastMessageId = latestVisibleMessageId\(\)/);
  assert.match(js, /const receivedNewVisibleMessage = previousLastMessageId !== nextLastMessageId/);
  assert.match(
    js,
    /!chatScrollState\.readingLongText\s*&&\s*\(\s*scrollToBottom\s*\|\|\s*shouldForceInitialBottomScroll\(\)\s*\|\|\s*\(chatScrollState\.nearBottom\s*&&\s*receivedNewVisibleMessage\)\s*\)/,
  );
  assert.match(js, /restoreChatScrollState\(chatScrollState\)/);
  assert.match(js, /refreshWorkspaceSurface\(\{ scrollToBottom: true }\)/);
  assert.match(js, /refreshWorkspaceSurface\(\{ scrollToBottom: false }\)\.catch/);
  assert.match(js, /themeToggle/);
  assert.match(js, /artifactErrors/);
  assert.match(js, /inputArtifactIds/);
  assert.match(js, /\/api\/artifacts\/\$\{encodeURIComponent/);
  assert.doesNotMatch(js, /runnerModeText/);
  assert.doesNotMatch(js, /artifactCountText/);
  assert.match(js, /function composerTargets/);
  assert.match(js, /return \["gpt"\]/);
  assert.doesNotMatch(js, /selectedTargetMode/);
  assert.doesNotMatch(js, /targetsForMode/);
  assert.doesNotMatch(js, /targetMode/);
  assert.doesNotMatch(js, /\/api\/chat\/turns/);
  assert.doesNotMatch(js, /\/api\/chat\/messages/);
  assert.doesNotMatch(js, /selectedTaskId/);
  assert.doesNotMatch(js, /directGptFileInput/);
  assert.doesNotMatch(js, /\/api\/chat\/replies/);
  assert.match(css, /\.message-user \.message-attachments/);
  assert.match(css, /\.image-gallery-strip/);
  assert.match(css, /\.image-gallery-strip-header/);
  assert.match(css, /\.preview-reader/);
  assert.match(css, /\.preview-reader[\s\S]*grid-template-rows: auto minmax\(0, 1fr\)/);
  assert.match(css, /\.preview-reader[\s\S]*height: min\(620px, calc\(100vh - 210px\)\)/);
  assert.match(css, /\.preview-reader-toolbar/);
  assert.match(css, /\.preview-reader-body/);
  assert.match(css, /\.preview-reader \.document-preview-body[\s\S]*max-height: none/);
  assert.match(css, /\.preview-reader \.document-preview-body[\s\S]*overflow: visible/);
  assert.match(css, /\.sheet-preview-scroll/);
  assert.match(css, /\.archive-filter-input/);
  assert.match(css, /\.message-status/);
  assert.match(css, /\.message-status-strip/);
  assert.match(css, /\.message-status-summary/);
  assert.match(css, /\.message-status-detail/);
  assert.match(css, /\.message-status-grid/);
  assert.match(css, /\.message-status-timeline/);
  assert.match(css, /\.message-status\[open\] \.message-status-summary::after/);
  assert.match(css, /\.message-actions/);
  assert.match(css, /\.message-failed:not\(\.message-user\) \.message-content/);
  assert.match(css, /\.message-user\.message-failed \.message-content/);
  assert.doesNotMatch(css, /(^|\n)\.message-failed \.message-content \{/);
  assert.match(css, /\.acceptance-panel/);
  assert.match(css, /\.acceptance-group/);
  assert.match(css, /\.acceptance-group-head/);
  assert.match(css, /\.workflow-banner/);
  assert.match(css, /\.onboarding-guide/);
  assert.match(css, /\.onboarding-steps/);
  assert.match(css, /\.self-check-button/);
  assert.match(css, /\.self-check-panel/);
  assert.match(css, /\.self-check-panel\[data-level="ready"\]/);
  const selfCheckPanelBlock = cssBlocks(".self-check-panel").find((block) => block.includes("display")) || "";
  assert.match(selfCheckPanelBlock, /display: grid;/);
  assert.doesNotMatch(selfCheckPanelBlock, /border-bottom/);
  assert.doesNotMatch(selfCheckPanelBlock, /calc\(\(100vw - 980px\)/);
  assert.match(css, /\.workflow-actions/);
  assert.match(css, /\.workflow-action-button/);
  assert.match(css, /\.workflow-banner\[data-level="blocked"\]/);
  assert.match(css, /\.workflow-next-step/);
  assert.match(css, /\.chain-status-panel/);
  assert.match(css, /\.chain-status-summary/);
  assert.match(css, /\[hidden\]\s*\{[\s\S]*display: none !important;/);
  assert.match(css, /\.chain-status-popover/);
  assert.match(css, /\.chain-status-panel\[open\] \.chain-status-popover/);
  assert.match(css, /\.chain-status-grid/);
  assert.match(css, /\.chain-status-item/);
  assert.match(css, /\.chain-status-actions/);
  assert.match(css, /\.chain-status-copy-button/);
  assert.match(css, /\.chain-status-value/);
  assert.match(css, /\.chain-status-value\.is-error/);
  const chainPanelBlock = cssBlocks(".chain-status-panel").find((block) => block.includes("display")) || "";
  assert.match(chainPanelBlock, /display: inline-flex;/);
  assert.match(chainPanelBlock, /overflow: visible;/);
  assert.doesNotMatch(chainPanelBlock, /border-bottom/);
  assert.doesNotMatch(chainPanelBlock, /padding: 10px max/);
  const chainPopoverBlock = cssBlocks(".chain-status-popover").find((block) => block.includes("position")) || "";
  assert.match(chainPopoverBlock, /position: absolute;/);
  assert.match(chainPopoverBlock, /display: none;/);
  assert.doesNotMatch(chainPopoverBlock, /max-width: 150px/);
  const statusLineBlock = cssBlocks(".status-line").find((block) => block.includes("overflow")) || "";
  assert.match(statusLineBlock, /overflow: hidden;/);
  const statusPillBlock = css.match(/\.status-line > span,\s*\.status-pill\s*\{[^}]*\}/)?.[0] || "";
  assert.match(statusPillBlock, /flex: 0 0 auto;/);
  assert.match(statusPillBlock, /max-width: 116px;/);
  assert.match(statusPillBlock, /overflow: hidden;/);
  assert.match(statusPillBlock, /text-overflow: ellipsis/);
  assert.match(css, /\.chain-status-summary[\s\S]*max-width: 112px;/);
  const acceptancePanelBlock = cssBlocks(".acceptance-panel").find((block) => block.includes("display")) || "";
  assert.match(acceptancePanelBlock, /display: flex;/);
  assert.match(acceptancePanelBlock, /padding: 8px max/);
  assert.match(css, /\.acceptance-panel\[hidden\]\s*\{[\s\S]*display: none;/);
  assert.match(css, /\.workflow-banner\s*\{[\s\S]*flex-wrap: wrap;/);
  assert.match(css, /\.routing-rule-state/);
  assert.match(css, /:root\[data-theme="light"\]\s*\{[\s\S]*--bg: #ffffff;/);
  assert.match(css, /:root\[data-theme="light"\]\s*\{[\s\S]*--surface: #ffffff;/);
  assert.match(css, /\.workflow-copy\s*\{[\s\S]*flex: 1 1 320px;/);
  assert.match(css, /\.workflow-side\s*\{[\s\S]*flex: 1 1 360px;/);
  assert.match(css, /\.workflow-actions\s*\{[\s\S]*flex-wrap: wrap;/);
  const workflowNextStepBlock =
    cssBlocks(".workflow-next-step").find((block) => block.includes("min-width")) || "";
  assert.match(workflowNextStepBlock, /min-width: min\(260px, 100%\);/);
  assert.match(workflowNextStepBlock, /overflow-wrap: break-word;/);
  assert.doesNotMatch(workflowNextStepBlock, /overflow-wrap: anywhere;/);
  assert.match(css, /\[data-gpt-blocked="true"\]/);
  assert.match(css, /\.chat-view\s*\{[\s\S]*display: flex;[\s\S]*flex-direction: column;[\s\S]*overflow: hidden;/);
  assert.doesNotMatch(css, /grid-template-rows: auto auto minmax\(0, 1fr\) auto auto/);
  assert.match(css, /\.message-list\s*\{[\s\S]*flex: 1 1 auto;/);
  assert.match(css, /\.message-list\s*\{[\s\S]*overflow-anchor: none;/);
  assert.match(css, /\.composer\s*\{[\s\S]*flex: 0 0 auto;/);
  const composerTextareaBlock = cssBlocks(".composer-box textarea").find((block) => block.includes("min-height")) || "";
  assert.match(composerTextareaBlock, /min-height: 38px;/);
  const composerBoxBlock = cssBlocks(".composer-box").find((block) => block.includes("padding")) || "";
  assert.match(composerBoxBlock, /padding: 10px 12px;/);
  const composerHintBlock = cssBlocks(".composer-block-hint").find((block) => block.includes("margin")) || "";
  assert.match(composerHintBlock, /margin: 0;/);
  assert.match(css, /\.send-button\[data-composer-blocked="true"\]/);
  assert.match(css, /\.composer-block-hint/);
  assert.match(css, /\.composer-block-hint\[hidden\]/);
  assert.match(css, /\.acceptance-item/);
  assert.match(css, /\.file-preview-shell/);
  assert.match(css, /\.file-card\.is-message-artifact/);
  assert.match(css, /\.artifact-icon-button/);
  assert.match(css, /\.dialog-actions/);
  assert.match(css, /\.acceptance-record-dialog/);
  assert.match(css, /\.acceptance-record-body/);
  assert.match(css, /\.text-preview/);
  assert.match(css, /\.code-file-preview/);
  assert.match(css, /\.code-file-preview-header/);
  assert.match(css, /\.code-file-preview pre/);
  assert.match(css, /\.longform-preview/);
  assert.match(css, /\.longform-preview-header/);
  assert.match(css, /\.longform-reader-body/);
  assert.match(css, /\.sheet-preview-table/);
  assert.match(css, /overflow-wrap: anywhere/);
  assert.match(css, /\.image-actions/);
  assert.match(css, /\.presentation-preview/);
  assert.match(css, /\.presentation-preview\.is-compact/);
  assert.match(css, /\.presentation-preview\.is-expanded/);
  assert.match(css, /\.presentation-slide-frame/);
  assert.match(css, /\.presentation-preview\.is-compact \.presentation-slide-frame/);
  assert.match(css, /\.presentation-slide-canvas/);
  assert.match(css, /\.pdf-preview iframe[\s\S]*max-height/);
  assert.match(css, /\.composer-footer-right[\s\S]*flex-wrap/);
  assert.match(css, /@media \(max-width: 720px\)/);
});

test("sync status distinguishes GPT thinking time from Bridge capture time", async () => {
  const js = await readFile("public/app.js", "utf8");
  const formatSyncProgressDuration = new Function(
    `${functionSource(js, "formatDurationMs")}
${functionSource(js, "reliableGptThoughtMs")}
${functionSource(js, "formatSyncProgressDuration")}
return formatSyncProgressDuration;`
  )();

  assert.equal(
    formatSyncProgressDuration({
      stage: "completed",
      durations: {
        responseMs: 33_000,
        gptThoughtMs: 19_000
      }
    }),
    "GPT 用时 19 秒 · Bridge 捕获 33 秒"
  );
});
